<?php
namespace Module\Sbpmakeplan\Models;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Module\SysAdmin\Models\SysSetup;

class SbpmakeplanTrans extends Model{
    protected $table = 'act_gvouc_trans_item';
    protected $primaryKey = 'TransID';

    public static function search(Request $request, $TransID){
        return 1;
    }
    protected $fillable = [
        'TransID',
        'AutoactID',
        'AccountID',
        'AccountNo',
        'CoAccountID',
        'CoAccountNo',
        'Description',
        'CcyID',
        'CcyNo',
        'CcyName',
        'ExchangeRate',
        'FCDebitAmount',
        'LCDebitAmount',
        'FCCreditAmount',
        'LCCreditAmount',
        'FCAmount',
        'LCAmount',
        'InTransTypeID',
        'InTransTypeName',
        'InvoiceSerialNo',
        'InvoiceFormNo',
        'InvoiceSecurityCode',
        'InvoiceLookupAddress',
        'Quantity',
        'FCUnitPrice',
        'LCUnitPrice',
        'EmployeeID',
        'EmployeeNo',
        'EmployeeName',
        'CustomerID',
        'CustomerNo',
        'CustomerName',
        'VendorID',
        'VendorNo',
        'VendorName',
        'PartnerID',
        'PartnerNo',
        'FullName',
        'RevenueID',
        'RevenueNo',
        'RevenueName',
        'ExpenseID',
        'ExpenseNo',
        'ExpenseName',
        'FundID',
        'FundNo',
        'FundName',
        'CapitalID',
        'CapitalNo',
        'CapitalName',
        'FiscalPeriod',
        'FiscalYear',
        'SbiChapterID',
        'SbiChapterNo',
        'SbiChapterName',
        'SbiCategoryID',
        'SbiCategoryNo',
        'SbiCategoryName',
        'SbiItemID',
        'SbiItemNo',
        'SbiItemName',
        'ProjectID',
        'ProjectNo',
        'TabmisNo',
        'ProjectName',
        'ContractID',
        'ContractNo',
        'ContractName',
        'FixedAssetID',
        'FixedAssetNo',
        'FixedAssetName',
        'ToolID',
        'ToolNo',
        'ToolName',
        'InvestAssetID',
        'InvestAssetNo',
        'InvestAssetName',
        'ItemID',
        'ItemNo',
        'ItemName',
        'NormTableID',
        'NormTableItemID',
        'NormTableItemNo',
        'NormTableItemName',
        'FCNormAmount',
        'LCNormAmount',
        'NormID',
        'TransTypeID',
        'FCRequestAmount',
        'LCRequestAmount',
        'FCReviewAmount',
        'LCReviewAmount',
        'FCApprovedAmount',
        'LCApprovedAmount',
        'FCAllocatedAmount',
        'LCAllocatedAmount',
        'FCAssignedAmount',
        'LCAssignedAmount',
        'FCGivedAmount',
        'LCGivedAmount',
        'FCPlanAmount',
        'LCPlanAmount',
        'PeriodType',
        'BudgetLevel',
        'ProgramType',
        'ProgramID',
        'ProgramNo',
        'ProgramName',
        'FCExecAmount',
        'LCExecAmount',
        'SectorID',
        'SectorNo',
        'SectorName',
        'SbrSectorID',
        'SbrSectorNo',
        'SbrSectorName',
        'InputCompanyID',
        'InputCompanyNo',
        'InputCompanyName'
    ];
    public $timestamps = false;

    public function actautoact(){
        return $this->belongsTo('Module\Sbpmakeplan\Models\Actautoact','AutoactID','AutoactID');
    }

}

?>
